[package]
name = "rmqtt-raft"
version = "0.1.0"
authors = ["rmqtt-rs <rmqttd@126.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/rmqtt-rs/rmqtt-raft"
description = "rmqtt-raft - A raft framework, for regular people"
keywords = ["raft", "distributed-systems"]

[dependencies]
futures = "0.3.16"
async-trait = "0.1.50"
bincode = "1.3"
log = { version = "0.4", features = ["std"] }
parking_lot = "0.11"
raft = { git = "https://github.com/tikv/raft-rs.git", rev = "eec5ead3ebe8f790154c94cb5f5adb0063a674e9", features = ["protobuf-codec"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
slog = "2"
thiserror = "1.0"
tokio = { version = "1.10", features = ["full"] }
tonic = "0.4"
prost = "0.7"
protobuf = { version = "2.14.0", features = ["with-bytes", "with-serde"] }
dashmap = "4.0.2"
ahash = "0.7.6"

[build-dependencies]
tonic-build = "0.4"

